spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 10000
      
      
app:
  auth:
     jwks-url: https://YOUR_DOMAIN/.well-known/jwks.json